### Create a user
POST http://localhost:8000/auth/register
Content-Type: application/json

{
  "name": "Admin",
  "email": "admin@example.com",
  "password": "123456",
  "address": "123 Main St",
  "role": "admin"
}

### login a user
POST http://localhost:8000/auth/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "123456"
}

### Create a product
POST http://localhost:8000/api/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MTRjNzI3OGFjYTBkZTAyZTIxOTZjZSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc0NjI2OTU0NCwiZXhwIjoxNzQ2MjczMTQ0fQ.sa2eyHTpRKi32anuSml56t_rfDBkwS9PtthjesAbL-A

{
    "name": "Admin Product 122",
    "description": "This is a test product description",
    "price": 999,
    "category": "electronics",
    "image": "test.jpg",
    "stock": 10
}

### Get all products
GET http://localhost:8000/api/products


### Get the admin page
GET http://localhost:8000/admin/
Authorization: Bearer <token>

