### Create an admin user
POST http://localhost:8000/auth/register
Content-Type: application/json

{
  "name": "Admin",
  "email": "admin@example.com",
  "password": "123456",
  "address": "123 Main St",
  "role": "admin"
}

### Create a normal user
POST http://localhost:8000/auth/register
Content-Type: application/json

{
  "name": "user",
  "email": "user@example.com",
  "password": "123456",
  "address": "123 Main St",
  "role": "customer"
}

### login an admin user
POST http://localhost:8000/auth/login
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "123456"
}

### login a normal user
POST http://localhost:8000/auth/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "123456"
}

### Create a product
POST http://localhost:8000/api/products
Content-Type: application/json
Authorization: Bearer <token>

{
    "name": "Admin Product 122",
    "description": "This is a test product description",
    "price": 999,
    "category": "electronics",
    "image": "test.jpg",
    "stock": 10
}


### Get all products
GET http://localhost:8000/api/products


### Update a product



### Delete a product



### Create a user



### Delete a user



### Get all users



### Get all orders



### Update an order status



### Add coupon



### Get all coupons



### Delete a coupon



### Get the admin page
GET http://localhost:8000/admin/
Authorization: Bearer <token>


### Get user profile



### view user's orders



### Add items to cart



### Remove items from cart



### increment item in cart



### decrement item in cart



### View cart items



### checkout cart items
