### Create an admin user
POST http://localhost:8000/auth/register
Content-Type: application/json

{
  "name": "Admin",
  "email": "admin@example.com",
  "password": "123456",
  "address": "123 Main St",
  "role": "admin"
}

### Create a normal user
POST http://localhost:8000/auth/register
Content-Type: application/json

{
  "name": "user",
  "email": "user@example.com",
  "password": "123456",
  "address": "123 Main St",
  "role": "customer"
}

### login an admin user
POST http://localhost:8000/auth/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "123456"
}

### login a normal user
POST http://localhost:8000/auth/login
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "123456"
}

### Create a product
POST http://localhost:8000/api/products
Content-Type: application/json
Authorization: Bearer <token>

{
    "name": "Admin Product 122",
    "description": "This is a test product description",
    "price": 999,
    "category": "electronics",
    "image": "test.jpg",
    "stock": 10
}


### Get all products
GET http://localhost:8000/api/products


### Update a product



### Delete a product



### Create a user



### Delete a user
DELETE http://localhost:8000/api/users/681746db11e0cd45faeffd8a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MTRjNzI3OGFjYTBkZTAyZTIxOTZjZSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc0NjM1NTg4OCwiZXhwIjoxNzQ2MzU5NDg4fQ.3I1OvGjNwKazOHiuyTNAK7UkK1uPNcs0Pcpzeojom9w


### Get all users
GET http://localhost:8000/api/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MTRjNzI3OGFjYTBkZTAyZTIxOTZjZSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc0NjM1NTg4OCwiZXhwIjoxNzQ2MzU5NDg4fQ.3I1OvGjNwKazOHiuyTNAK7UkK1uPNcs0Pcpzeojom9w


### Get a user by ID
GET http://localhost:8000/api/users/681714155b2cd91efd012d43
Authorization: Bearer <token>


### Get all orders



### Update an order status



### Add coupon



### Get all coupons



### Delete a coupon



### Get the admin page
GET http://localhost:8000/admin/
Authorization: Bearer <token>


### Get user profile
GET http://localhost:8000/api/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MTcxNDE1NWIyY2Q5MWVmZDAxMmQ0MyIsInJvbGUiOiJjdXN0b21lciIsImlhdCI6MTc0NjM1NTcwMCwiZXhwIjoxNzQ2MzU5MzAwfQ.fn9somUVjjKqZtbIjc6_ozAtGxPsp3fzz0pzNrr7NBE


### Update user profile
PUT http://localhost:8000/api/users/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MTcxNDE1NWIyY2Q5MWVmZDAxMmQ0MyIsInJvbGUiOiJjdXN0b21lciIsImlhdCI6MTc0NjM1NTcwMCwiZXhwIjoxNzQ2MzU5MzAwfQ.fn9somUVjjKqZtbIjc6_ozAtGxPsp3fzz0pzNrr7NBE

{
  "name": "Updated User",
  "email": "user@example.com",
  "address": "123 New Street"
}


### view user's orders


### Add items to cart



### Remove items from cart



### increment item in cart



### decrement item in cart



### View cart items



### checkout cart items
