### Create an admin user
POST http://localhost:8000/auth/register
Content-Type: application/json

{
  "name": "Admin",
  "email": "admin@example.com",
  "password": "123456",
  "address": "123 Main St",
  "role": "admin"
}

### login an admin user
POST http://localhost:8000/auth/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "123456"
}


### Create a product
POST http://localhost:8000/api/products
Content-Type: application/json
Authorization: Bearer <token>
{
    "name": "Product 133",
    "description": "This is a product 133 description",
    "price": 60,
    "category": "electronics",
    "image": "test.jpg",
    "stock": 10
}


### Get all products
GET http://localhost:8000/api/products

### Get a product by ID
GET http://localhost:8000/api/products/6815da9a334e81baa5b0d947


### Update a product by ID (product_id)
PUT http://localhost:8000/api/products/6815da9a334e81baa5b0d947
Authorization: Bearer <token>
Content-Type: application/json

{
  "code": "A34GH",
  "percentage": 10
}


### Delete a product by ID (product_id)
DELETE http://localhost:8000/api/products/6815daf766883949325a1bf5
Authorization: Bearer <token>


### Delete a user (user_id)
DELETE http://localhost:8000/api/users/6817471711e0cd45faeffd96
Authorization: Bearer <token>


### Get all users
GET http://localhost:8000/api/users/
Authorization: Bearer <token>


### Get a user by ID (user_id)
GET http://localhost:8000/api/users/681714155b2cd91efd012d43
Authorization: Bearer <token>


### Get all orders
GET http://localhost:8000/api/orders
Authorization: Bearer <token>

### Update an order status (order_id)
PUT http://localhost:8000/api/orders/6817f0314c102114b0b87910
Content-Type: application/json
Authorization: Bearer <token>

{
  "status": "shipped"
}

### Create coupon
POST http://localhost:8000/api/coupons
Content-Type: application/json
Authorization: Bearer <token>

{
    "code": "A34GH",
    "percentage": 10
}


### Get all coupons
GET http://localhost:8000/api/coupons
Authorization: Bearer <token>


### Delete a coupon
DELETE http://localhost:8000/api/coupons/6817e67ddab05b80be4dc154
Authorization: Bearer <token>


### Get the admin page
GET http://localhost:8000/admin/
Authorization: Bearer <token>