### Create a normal user                                              Dooooooooooooooooone
POST http://localhost:8000/auth/register
Content-Type: application/json

{
  "name": "user",
  "email": "user@example.com",
  "password": "123456",
  "address": "123 Main St",
  "role": "customer"
}

### login a normal user                                              Dooooooooooooooooone
POST http://localhost:8000/auth/login
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "123456"
}

### Get all products                                              Dooooooooooooooooone
GET http://localhost:8000/api/products


### Get user profile                                              Dooooooooooooooooone
GET http://localhost:8000/api/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MThlZmUyNDBiNWVmZmE0OTkxMmM5YiIsInJvbGUiOiJjdXN0b21lciIsImlhdCI6MTc0NjQ4MTQwMSwiZXhwIjoxNzQ2NDg1MDAxfQ.GIwdMfoukTCKbBpuHkbt3YgBdbr4lLbsVOn3bTmAsXA


### Update user profile                                              Dooooooooooooooooone
PUT http://localhost:8000/api/users/profile
Content-Type: application/json
Authorization: Bearer <token>

{
  "name": "Updated User",
  "email": "user@example.com",
  "address": "123 New Street"
}


### Add items to cart (product_id)
POST http://localhost:8000/api/products/add-to-cart/#######
Content-Type: application/json
Authorization: Bearer <token>

{
  "quantity": 1
}

### Remove items from cart (cartItem_id)
DELETE http://localhost:8000/api/cart/6817c79a1d9bb4a6f4fa6587
Authorization: Bearer <token>

### Increment item in cart (cartItem_id)
PUT http://localhost:8000/api/cart/increment/6817faebf3e23650211a537d
Authorization: Bearer <token>

### Decrement item in cart (cartItem_id)
PUT http://localhost:8000/api/cart/decrement/6817efa193c8616cf9a0784e
Authorization: Bearer <token>


### View cart items
GET http://localhost:8000/api/cart
Authorization: Bearer <token>


### Checkout cart items
POST http://localhost:8000/api/cart/checkout
Content-Type: application/json
Authorization: Bearer <token>

{
  "code": "A34GH"
}

### View user's orders
GET http://localhost:8000/api/orders/user-orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MWJhMjk5ZmU2NDAxMmM0N2YzNWIzMiIsInJvbGUiOiJjdXN0b21lciIsImlhdCI6MTc0NjcxOTY1MiwiZXhwIjoxNzQ2NzIzMjUyfQ.t_7o-nS3V1q-YS2ZbKAzvpeZy0CPvgMaBPwWkvHQpvw

### Add product review (product_id)
POST http://localhost:8000/api/products/review/681a75bee907710d40186e77
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MWM1YjVmYTU5NjVlMWNjMTdjOGNlZiIsInJvbGUiOiJjdXN0b21lciIsImlhdCI6MTc0NjY4ODg2NSwiZXhwIjoxNzQ2NjkyNDY1fQ.lCIHnOEOqiJlSt4gUyw4Nq2X2eQ1-haFCtiN3usXKuA

{
  "rating": 4,
  "review": "Good product!"
}

### Update product review (product_id)
PUT http://localhost:8000/api/products/review/6817f9f9f3e23650211a5353
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MTdjNWRlNDc0MTljMzg3ZjI0MDJjOCIsInJvbGUiOiJjdXN0b21lciIsImlhdCI6MTc0NjQwMTgyOSwiZXhwIjoxNzQ2NDA1NDI5fQ.vGaxOWFp6zFFnACCeE9JBvjsIa8qwMFCw-TKaSmA3Js

{
  "rating": 2,
  "review": "Bad product!"
}

### View product reviews (product_id)
GET http://localhost:8000/api/products/reviews/681a75bee907710d40186e77

### Delete a review by review ID (user)
DELETE http://localhost:8000/api/products/review/id/<review_id>
Authorization: Bearer <user_token>
