### Create a normal user
POST http://localhost:8000/auth/register
Content-Type: application/json

{
  "name": "user",
  "email": "user@example.com",
  "password": "123456",
  "address": "123 Main St",
  "role": "customer"
}

### login a normal user
POST http://localhost:8000/auth/login
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "123456"
}

### Get all products
GET http://localhost:8000/api/products


### Get user profile
GET http://localhost:8000/api/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MTdjNWRlNDc0MTljMzg3ZjI0MDJjOCIsInJvbGUiOiJjdXN0b21lciIsImlhdCI6MTc0NjQwMTgyOSwiZXhwIjoxNzQ2NDA1NDI5fQ.vGaxOWFp6zFFnACCeE9JBvjsIa8qwMFCw-TKaSmA3Js


### Update user profile
PUT http://localhost:8000/api/users/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MTcxNDE1NWIyY2Q5MWVmZDAxMmQ0MyIsInJvbGUiOiJjdXN0b21lciIsImlhdCI6MTc0NjM1NTcwMCwiZXhwIjoxNzQ2MzU5MzAwfQ.fn9somUVjjKqZtbIjc6_ozAtGxPsp3fzz0pzNrr7NBE

{
  "name": "Updated User",
  "email": "user@example.com",
  "address": "123 New Street"
}


### Add items to cart
POST http://localhost:8000/api/products/add-to-cart/6817f9f9f3e23650211a5353
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MTdjNWRlNDc0MTljMzg3ZjI0MDJjOCIsInJvbGUiOiJjdXN0b21lciIsImlhdCI6MTc0NjQwMTgyOSwiZXhwIjoxNzQ2NDA1NDI5fQ.vGaxOWFp6zFFnACCeE9JBvjsIa8qwMFCw-TKaSmA3Js

{
  "quantity": 1
}

### Remove items from cart
DELETE http://localhost:8000/api/cart/6817c79a1d9bb4a6f4fa6587
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MTdjNWRlNDc0MTljMzg3ZjI0MDJjOCIsInJvbGUiOiJjdXN0b21lciIsImlhdCI6MTc0NjM4ODQ2NiwiZXhwIjoxNzQ2MzkyMDY2fQ.kcgUHW-VLgvcf3Afct2Z4TahYU3f2-dwBp0oreaH4Vo


### Increment item in cart
PUT http://localhost:8000/api/cart/increment/6817faebf3e23650211a537d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MTdjNWRlNDc0MTljMzg3ZjI0MDJjOCIsInJvbGUiOiJjdXN0b21lciIsImlhdCI6MTc0NjQwMTgyOSwiZXhwIjoxNzQ2NDA1NDI5fQ.vGaxOWFp6zFFnACCeE9JBvjsIa8qwMFCw-TKaSmA3Js

### Decrement item in cart
PUT http://localhost:8000/api/cart/decrement/6817efa193c8616cf9a0784e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MTdjNWRlNDc0MTljMzg3ZjI0MDJjOCIsInJvbGUiOiJjdXN0b21lciIsImlhdCI6MTc0NjM5NTMzNywiZXhwIjoxNzQ2Mzk4OTM3fQ.U_gyTRw9EJ7nC4i-Gk0_nPir4NXKJ3p5UDdhFUS6ktU


### View cart items
GET http://localhost:8000/api/cart
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MTdjNWRlNDc0MTljMzg3ZjI0MDJjOCIsInJvbGUiOiJjdXN0b21lciIsImlhdCI6MTc0NjQwMTgyOSwiZXhwIjoxNzQ2NDA1NDI5fQ.vGaxOWFp6zFFnACCeE9JBvjsIa8qwMFCw-TKaSmA3Js


### Checkout cart items
POST http://localhost:8000/api/cart/checkout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MTdjNWRlNDc0MTljMzg3ZjI0MDJjOCIsInJvbGUiOiJjdXN0b21lciIsImlhdCI6MTc0NjQwMTgyOSwiZXhwIjoxNzQ2NDA1NDI5fQ.vGaxOWFp6zFFnACCeE9JBvjsIa8qwMFCw-TKaSmA3Js

{
  "code": "A34GH"
}

### View user's orders
GET http://localhost:8000/api/orders/user-orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MTdjNWRlNDc0MTljMzg3ZjI0MDJjOCIsInJvbGUiOiJjdXN0b21lciIsImlhdCI6MTc0NjQwMTQ0NiwiZXhwIjoxNzQ2NDA1MDQ2fQ.OQtFm0XPjgZKjftFDa6OCP-GGqY9d2yfA0f2rHX5_dc

### Add product review
POST http://localhost:8000/api/products/review/6817f9f9f3e23650211a5353
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MTdjNWRlNDc0MTljMzg3ZjI0MDJjOCIsInJvbGUiOiJjdXN0b21lciIsImlhdCI6MTc0NjQwMTgyOSwiZXhwIjoxNzQ2NDA1NDI5fQ.vGaxOWFp6zFFnACCeE9JBvjsIa8qwMFCw-TKaSmA3Js

{
  "rating": 4,
  "review": "Good product!"
}

### Update product review
PUT http://localhost:8000/api/products/review/6817f9f9f3e23650211a5353
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MTdjNWRlNDc0MTljMzg3ZjI0MDJjOCIsInJvbGUiOiJjdXN0b21lciIsImlhdCI6MTc0NjQwMTgyOSwiZXhwIjoxNzQ2NDA1NDI5fQ.vGaxOWFp6zFFnACCeE9JBvjsIa8qwMFCw-TKaSmA3Js

{
  "rating": 2,
  "review": "Bad product!"
}

### View product reviews
GET http://localhost:8000/api/products/reviews/6817f9f9f3e23650211a5353